import {
  Activity,
  AirVent,
  Ambulance,
  Apple,
  Armchair,
  ArrowRight,
  AtSign,
  Award,
  Baby,
  BedDouble,
  Bike,
  BookOpen,
  BookOpenCheck,
  Bone,
  Brain,
  Briefcase,
  Building2,
  CalendarCheck,
  CalendarClock,
  Camera,
  Car,
  CheckCircle2,
  ClipboardList,
  Clock,
  Coffee,
  Contact,
  Dumbbell,
  Eye,
  Glasses,
  Globe,
  GraduationCap,
  HandHeart,
  Heart,
  HeartPulse,
  HeartHandshake,
  HelpCircle,
  Home,
  Hospital,
  Hourglass,
  Languages,
  Laptop,
  Leaf,
  LifeBuoy,
  Lightbulb,
  Mail,
  MapPin,
  MessageCircle,
  Microscope,
  MonitorPlay,
  Moon,
  Music,
  Newspaper,
  Package,
  Palette,
  Phone,
  PhoneCall,
  Pill,
  Plane,
  Quote,
  Shield,
  ShieldCheck,
  Smile,
  Sparkles,
  SquarePlay,
  Star,
  Stethoscope,
  Sun,
  Syringe,
  Users,
  Video,
  Wallet,
  Wifi,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Curated icon catalog for the admin icon picker. Names are stored as plain
 * strings in site content and resolved back to components here — public
 * components never import lucide icons dynamically.
 */
export const ICON_CATALOG: Array<{ name: string; Icon: LucideIcon }> = [
  { name: "heart-pulse", Icon: HeartPulse },
  { name: "stethoscope", Icon: Stethoscope },
  { name: "activity", Icon: Activity },
  { name: "hospital", Icon: Hospital },
  { name: "ambulance", Icon: Ambulance },
  { name: "pill", Icon: Pill },
  { name: "syringe", Icon: Syringe },
  { name: "microscope", Icon: Microscope },
  { name: "baby", Icon: Baby },
  { name: "brain", Icon: Brain },
  { name: "bone", Icon: Bone },
  { name: "eye", Icon: Eye },
  { name: "smile", Icon: Smile },
  { name: "heart", Icon: Heart },
  { name: "hand-heart", Icon: HandHeart },
  { name: "heart-handshake", Icon: HeartHandshake },
  { name: "calendar-check", Icon: CalendarCheck },
  { name: "calendar-clock", Icon: CalendarClock },
  { name: "clock", Icon: Clock },
  { name: "hourglass", Icon: Hourglass },
  { name: "phone", Icon: Phone },
  { name: "phone-call", Icon: PhoneCall },
  { name: "mail", Icon: Mail },
  { name: "map-pin", Icon: MapPin },
  { name: "globe", Icon: Globe },
  { name: "at-sign", Icon: AtSign },
  { name: "message-circle", Icon: MessageCircle },
  { name: "contact", Icon: Contact },
  { name: "users", Icon: Users },
  { name: "graduation-cap", Icon: GraduationCap },
  { name: "award", Icon: Award },
  { name: "star", Icon: Star },
  { name: "sparkles", Icon: Sparkles },
  { name: "shield", Icon: Shield },
  { name: "shield-check", Icon: ShieldCheck },
  { name: "check-circle", Icon: CheckCircle2 },
  { name: "zap", Icon: Zap },
  { name: "leaf", Icon: Leaf },
  { name: "sun", Icon: Sun },
  { name: "moon", Icon: Moon },
  { name: "apple", Icon: Apple },
  { name: "coffee", Icon: Coffee },
  { name: "dumbbell", Icon: Dumbbell },
  { name: "bike", Icon: Bike },
  { name: "armchair", Icon: Armchair },
  { name: "bed", Icon: BedDouble },
  { name: "air-vent", Icon: AirVent },
  { name: "briefcase", Icon: Briefcase },
  { name: "building", Icon: Building2 },
  { name: "home", Icon: Home },
  { name: "car", Icon: Car },
  { name: "plane", Icon: Plane },
  { name: "laptop", Icon: Laptop },
  { name: "camera", Icon: Camera },
  { name: "video", Icon: Video },
  { name: "monitor-play", Icon: MonitorPlay },
  { name: "square-play", Icon: SquarePlay },
  { name: "music", Icon: Music },
  { name: "palette", Icon: Palette },
  { name: "book-open", Icon: BookOpen },
  { name: "book-open-check", Icon: BookOpenCheck },
  { name: "newspaper", Icon: Newspaper },
  { name: "clipboard-list", Icon: ClipboardList },
  { name: "package", Icon: Package },
  { name: "wallet", Icon: Wallet },
  { name: "wifi", Icon: Wifi },
  { name: "languages", Icon: Languages },
  { name: "lightbulb", Icon: Lightbulb },
  { name: "glasses", Icon: Glasses },
  { name: "help-circle", Icon: HelpCircle },
  { name: "life-buoy", Icon: LifeBuoy },
  { name: "quote", Icon: Quote },
  { name: "arrow-right", Icon: ArrowRight },
];

const ICON_MAP = new Map(ICON_CATALOG.map((entry) => [entry.name, entry.Icon]));

/** Resolve a stored icon name to a component, or undefined when empty/unknown. */
export function iconByName(name: string | null | undefined): LucideIcon | undefined {
  if (!name) return undefined;
  return ICON_MAP.get(name);
}
